"use client";

import TripHistoryTable from '@/components/battery-monitoring/TripHistoryTable';
import SOCTrendsChart from '@/components/battery-monitoring/SOCTrendsChart';
import { Card, Text } from '@tremor/react';

/**
 * Fleet Trip Analytics Page — enhanced with SOC Trends (#87)
 */
export default function TripsAnalyticsPage() {
    return (
        <div className="max-w-7xl mx-auto space-y-6">
            <div>
                <h1 className="text-3xl font-extrabold tracking-tight text-gray-900">
                    Fleet Trip Analytics
                </h1>
                <p className="mt-1 text-sm text-gray-500">
                    Analyze recent trips across the entire mapped fleet. Evaluate distance traveled and energy efficiency ratings.
                </p>
            </div>

            {/* SOC Trends Chart */}
            <SOCTrendsChart days={30} />

            <div className="grid grid-cols-1 gap-6">
                <Card decoration="top" decorationColor="blue">
                    <Text className="mb-4">Recent tracking summary of historical trips generated by devices. Detailed maps for each trip will be available in the vehicle breakdown.</Text>
                    <TripHistoryTable limit={50} />
                </Card>
            </div>
        </div>
    );
}
